image: cypress/base:12.14.0

stages:
  - build
  - test
  - report

variables:
  ALLURE_VERSION: '2.13.8'

install_dependencies:
  stage: build
  script:
    - npm install

run_cypress_tests:
  stage: test
  script:
    - $(npm bin)/cypress run --reporter cypress-allure-plugin

generate_allure_report:
  stage: report
  script:
    - wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz -O /tmp/allure-$ALLURE_VERSION.tgz
    - tar -zxvf /tmp/allure-$ALLURE_VERSION.tgz -C /tmp/
    - /tmp/allure-$ALLURE_VERSION/bin/allure generate allure-results --clean -o allure-report
  artifacts:
    paths:
      - allure-report/