name: Execução automação de testes

on:
  pull_request:
      types: [synchronize]
      paths-ignore:
        - '**.md'
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      teste:
        description: 'Selecionar testes a serem executados: roteiro / test'
        required: true
        default: 'test'
      browser:
        description: 'Selecionar o browser: chrome / electron / firefox'
        required: false
        default: 'chrome'

env:
  DEFAULT_TESTE: "roteiro"
  DEFAULT_BROWSER: "chrome"

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - uses: actions/checkout@v2
      - run: npm install
         
        # Etapa de criação das pastas
      - run: mkdir -p cypress/videos
      - run: mkdir -p cypress/screenshots
      - run: mkdir -p cypress/report
    # Configuração da permissão
      - run: chmod -R a+w cypress/videos
      - run: chmod -R a+w cypress/screenshots
      - run:  chmod -R a+w cypress/report
      - name: Debug info
        run: |
            echo "PATH: $PATH"
            echo "Node.js version: $(node --version)"
            echo "npx version: $(npx --version)"
      - name: Cypress run 
        # uses: cypress-io/github-action@v2
        run: |
          echo "Executando comando"
          npm run cypress:allure
        shell: bash
          # command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
      
      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: allure-history
          keep_files: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      # - name: send message DISCORD Falha
      #   if: failure()
      #   run: |- 
      #     curl --request POST  --url ${{ secrets.WEBHOOK_URL_DISCORD }} --header 'Content-Type: application/json'  --data '{"content": "Notificação da esteitra de testes:","embeds": [{"title": "A execução apresentou uma falha!","description": "Para mais detalhes  [clique aqui](https://bookish-telegram-45f22f1c.pages.github.io/).","color": 8588082}]}'

      # - name: send message DISCORD Sucesso
      #   if: success()
      #   run: |-
      #     curl --request POST  --url ${{ secrets.WEBHOOK_URL_DISCORD }} --header 'Content-Type: application/json'  --data '{"content": "Notificação da esteitra de testes:","embeds": [{"title": "Execução realizada com sucesso!","description": "Para mais detalhes  [clique aqui](https://bookish-telegram-45f22f1c.pages.github.io/).","color": 1007112}]}'